### ISSUE TITLE
weston-terminal segfault

### ISSUE THREAD

**Issue by tripzero** [intel/ias#40] opened 2019-01-15 18:13 UTC
When running on clearlinux:

`/usr/share/ias/examples/weston-terminal`

Results in segfault.  Other examples work fine (ie weston-simple-egl).

**Comment by satyeshwar** [comment] 2019-01-23 21:08
Can't reproduce this issue. Need some more details please:
1) What HW? 
2) What was the build (ideally SHA commit id) that you used?
3) Did you have a keyboard connected to the system?
4) Did you run weston-terminal as ias user or root?

**Comment by tripzero** [comment] 2019-01-24 00:21
1. reproducible on APL NUC
2. e0a4975 4.0.14
3. no keyboard
4. ias user

**Comment by xinyunliu** [comment] 2019-01-25 03:07
I met the issue with clearlinux on APL MRB, too.

**Comment by satyeshwar** [comment] 2019-01-28 20:59
Please export WESTON_DATA_DIR=/usr/share/ias before running your tests. It works on my system and also confirmed by tripzero. Therefore, closing this defect.

**Comment by tripzero** [comment] 2019-01-28 21:03
Yep. Confirmed here.

**Closed as completed** 2019-01-28 21:16 UTC

**Comment by oidapala** [comment] 2019-01-30 06:38
Weston terminal is coming but not able to interact with that. Is the functionality implemented ? or is it expected

**Comment by satyeshwar** [comment] 2019-01-30 07:53
So, IAS is an automotive compositor. It is first and foremost meant for bootup speed. You don't expect there to be a keyboard in a car and a terminal like app with which you are interfacing (that would just be silly :-)). 
One of the things that we removed from open source Weston code when we were building IAS was the keyboard map compilation step. This saves us on a lot of time while IAS is booting up. Without a keyboard map, unfortunately  your key strokes cannot make sense to an app.  If you do want to type commands in, then you will need to do a few things:
1) Recompile IAS with --enable_xkbcommon option provided to autogen.sh
2) Provide your keyboard map to /usr/share/X11/xkb (this depends upon how libxkbcommon was built)
3) Remove raw_keyboards='1' option from ias.conf
4) Have a physical keyboard connected to the system.

As an experiment, you can try doing steps 1 and 2. That way, IAS will be built with xkbcommon (so the binary size will increase slightly and booting will be a bit slower). And then you can just turn raw_keyboards to 0 or 1 dependent upon if you want to see key strokes going to terminal or other apps.
