### ISSUE TITLE
ias-weston compositing can stop with mixed privilege workloads

### ISSUE THREAD

**Issue by mpfife** [intel/ias#45] opened 2019-01-25 00:37 UTC
Weston compositing seems to stop in the following combination. Weston and weston applications all seem to be alive and still submitting frames, but weston compositing stops and simply displays the last frame.

Steps to reproduce:
1. Start weston as a non-sudo/non-root user
2. Start one or more weston graphics apps (opengl in my case) as a normal user/non-sudo/non-root.
3. Start a single weston graphics app (OpenGL in my case) as root/sudo. 

Notes:
-When the root/sudo'ed app in step 3 is run, the hang can occur at some point after. It is not always immediate and doesn't always happen. 
-If the app from step 3 is a very high frame rate (700+ fps), then the compositing freeze happens almost immediately.
-In my testing, the root application in step 3 also used the OpenGL context creation flag EGL_CONTEXT_PRIORITY_HIGH_IMG to give the priority hint as high

Workarounds: running weston compositor as root/sudo seems to mitigate the problem.

**Comment by satyeshwar** [comment] 2019-02-01 00:25
Need some help in reproducing this issue (even though I saw it on your system).
1) How did you start IAS as non-root user. I simply do systemctl start ias. This launches it as ias user. Is that the same as what you did?
2) I then ran weston-simple-egl as ias user and weston-simple-shm as root user. Both ran without any issues.

I am unable to run stress-weston as I can't compile it. Any other steps to try?

**Comment by satyeshwar** [comment] 2019-02-07 23:13
Still can't reproduce it. Using 27450 version of CL (no other changes, no special setup like for CES demo). 
Just running IAS through systemd as ias user. Running two versions of stress-weston with no changes to params.txt so it runs standard dials. One is run as ias user and another is run as high priority with root access. Both run fine.

**Comment by satyeshwar** [comment] 2019-02-26 00:32
Unable to reproduce, so closing this defect. May reopen it if I get any new instructions to reproduce.

**Closed as completed by satyeshwar** 2019-02-26 00:32 UTC
